// my avatars
export const GET_ALL_MY_AVATARS = 'GET_ALL_MY_AVATARS'
export const ADD_MY_AVATAR = 'ADD_MY_AVATAR'
export const UPDATE_MY_AVATAR = 'UPDATE_MY_AVATAR'
export const REMOVE_MY_AVATAR = 'REMOVE_MY_AVATAR'

// templates
export const GET_ALL_TEMPLATES = 'GET_ALL_TEMPLATES'
export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE'
